###local host add contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
    "firstName": "Yuki",
    "lastName": "Chang",
    "email": "working@onit.com",
    "favoriteColor": "Black",
    "birthday": "1/31/24"
}
###

### Local host get all contacts
GET http://localhost:8080/contacts
###

###local host update contact
PUT http://localhost:8080/contacts/65b585bd6ddc914a35ebcb45
Content-Type: application/json

{
    "firstName": "Gracey",
    "lastName": "Chang",
    "email": "sweet@girl.com",
    "favoriteColor": "Purple",
    "birthday": "1/26/24"
}
###

### Local host get all contacts
GET http://localhost:8080/contacts
###


###local host delete contact
DELETE http://localhost:8080/contacts/65b598a516bcc3dfc28d49fb
###

### Local host get all contacts
GET http://localhost:8080/contacts
###




###render add contact
POST https://cse341byuiweek2.onrender.com/contacts/addContact
Content-Type: application/json

{
    "firstName": "Alex",
    "lastName": "Chang",
    "email": "great@student.com",
    "favoriteColor": "Purple",
    "birthday": "1/19/24"
}
###

### render get all contacts
GEt https://cse341byuiweek2.onrender.com/contacts
###

###render update contact
PUT https://cse341byuiweek2.onrender.com/contacts/updateContact/65b585bd6ddc914a35ebcb45
Content-Type: application/json

{
    "firstName": "Gracey",
    "lastName": "Chang",
    "email": "gracey@sweetgirl.com",
    "favoriteColor": "Gray",
    "birthday": "1/24/24"
}
###

### render get all contacts
GEt https://cse341byuiweek2.onrender.com/contacts
###

### render delete contact
DELETE  https://cse341byuiweek2.onrender.com/contacts/deleteContact/65b598fd2f6a200fccc73f37
###






###old stuff get by id local and on render


### local host get contacts by id
GET http://localhost:8080/contacts/65b5855a6ddc914a35ebcb43
###

GET http://localhost:8080/contacts/65b5859c6ddc914a35ebcb44
###

GET http://localhost:8080/contacts/65b585bd6ddc914a35ebcb45
###


### render get contacts by id
https://cse341byuiweek2.onrender.com/contacts/65b5855a6ddc914a35ebcb43
###

https://cse341byuiweek2.onrender.com/contacts/65b5859c6ddc914a35ebcb44
###

https://cse341byuiweek2.onrender.com/contacts/65b585bd6ddc914a35ebcb45
###

